# Generated by Django 2.2.16 on 2021-02-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placeholder', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
