# Generated by Django 2.2.16 on 2021-02-07 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210207_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocknote',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api', to=settings.AUTH_USER_MODEL),
        ),
    ]
